# Generated by Django 5.2 on 2025-12-06 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=100, verbose_name='Account ID')),
                ('applicant_name', models.CharField(max_length=200, verbose_name='Name of Applicant')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Unknown', 'Unknown'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Requested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
