# Generated by Django 5.2 on 2025-12-05 00:25

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='Unique user identifier (links to CreditAccount)', max_length=255, unique=True, validators=[core.validators.validate_account_id])),
                ('name', models.CharField(blank=True, help_text='Full name of the user', max_length=255, null=True)),
                ('school_name', models.CharField(blank=True, help_text='Previous school/institution name', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Full address', null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Whether profile is complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='user_profil_user_id_4f95f8_idx'), models.Index(fields=['email'], name='user_profil_email_27350e_idx'), models.Index(fields=['is_complete'], name='user_profil_is_comp_cf18d2_idx')],
            },
        ),
    ]
