# Generated by Django 5.2 on 2025-12-06 03:54

import core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('account_id', models.CharField(help_text='Unique account identifier', max_length=100, primary_key=True, serialize=False, validators=[core.validators.validate_account_id])),
                ('account_pass', models.CharField(blank=True, help_text='Hashed password for student accounts, plain text for faculty/admin (legacy)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Admin', 'Admin')], db_index=True, default='Student', help_text='Account type/role', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Credit Account',
                'verbose_name_plural': 'Credit Accounts',
                'db_table': 'credit_account',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='credit_acco_status_977c4a_idx'), models.Index(fields=['is_active'], name='credit_acco_is_acti_4048e1_idx'), models.Index(fields=['created_at'], name='credit_acco_created_2c752b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='Email address used for authentication', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_custom_user',
                'indexes': [models.Index(fields=['email'], name='auth_custom_email_42c5c2_idx'), models.Index(fields=['is_active', 'is_staff'], name='auth_custom_is_acti_4a284c_idx')],
            },
        ),
    ]
