# Generated by Django 5.2 on 2025-12-05 00:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorTransferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, default='', help_text='Student account identifier', max_length=100, validators=[core.validators.validate_account_id])),
                ('student_name', models.CharField(help_text='Full name of the student', max_length=100)),
                ('school_name', models.CharField(help_text='Name of previous institution', max_length=255)),
                ('subject_code', models.CharField(db_index=True, help_text='Subject/course code', max_length=50)),
                ('subject_description', models.CharField(help_text='Full subject description', max_length=255)),
                ('student_year', models.CharField(help_text='Year level when taken', max_length=20)),
                ('pre_requisite', models.CharField(blank=True, help_text='Pre-requisite subjects', max_length=255, null=True)),
                ('co_requisite', models.CharField(blank=True, help_text='Co-requisite subjects', max_length=255, null=True)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('summer', 'Summer')], help_text='Semester when taken', max_length=10)),
                ('school_year_offered', models.CharField(help_text='Academic year (e.g., 2023-2024)', max_length=20)),
                ('total_academic_units', models.FloatField(help_text='Number of academic units/credits', validators=[core.validators.validate_units])),
                ('final_grade', models.FloatField(help_text='Final grade received', validators=[core.validators.validate_grade])),
                ('remarks', models.CharField(blank=True, help_text='Additional remarks (PASSED/FAILED)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TOR Transferee',
                'verbose_name_plural': 'TOR Transferees',
                'db_table': 'tor_transferee',
                'ordering': ['account_id', 'subject_code'],
                'indexes': [models.Index(fields=['account_id', 'subject_code'], name='tor_transfe_account_df0e10_idx'), models.Index(fields=['student_name'], name='tor_transfe_student_a2022e_idx'), models.Index(fields=['created_at'], name='tor_transfe_created_d20971_idx')],
            },
        ),
    ]
