# Generated by Django 5.2 on 2025-12-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tortransferee',
            name='co_requisite',
            field=models.CharField(blank=True, help_text='Co-requisite subjects', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tortransferee',
            name='pre_requisite',
            field=models.CharField(blank=True, help_text='Pre-requisite subjects', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tortransferee',
            name='subject_description',
            field=models.CharField(help_text='Full subject description', max_length=500),
        ),
    ]
