# Generated by Django 5.2 on 2025-12-08 11:55

import core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listFinalTor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(db_index=True, max_length=100, validators=[core.validators.validate_account_id], verbose_name='Account ID')),
                ('applicant_name', models.CharField(max_length=200, verbose_name='Name of Applicant')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Unknown', 'Unknown'), ('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Finalized', 'Finalized')], db_index=True, default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Requested')),
                ('accepted_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Final TOR',
                'verbose_name_plural': 'Final TORs',
                'db_table': 'list_final_tor',
                'ordering': ['-accepted_date'],
                'indexes': [models.Index(fields=['accountID'], name='list_final__account_a2cf09_idx'), models.Index(fields=['status'], name='list_final__status_71a315_idx')],
            },
        ),
    ]
