# Generated by Django 5.2 on 2025-12-05 00:23

import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitTorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, help_text='Official subject code', max_length=30, unique=True)),
                ('prerequisite', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text='List of prerequisite subject codes', size=None)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='List of subject description variations', size=None)),
                ('units', models.PositiveIntegerField(help_text='Required academic units')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CIT TOR Content',
                'verbose_name_plural': 'CIT TOR Contents',
                'db_table': 'cit_tor_content',
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='CompareResultTOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, help_text='Student account identifier', max_length=100, validators=[core.validators.validate_account_id])),
                ('subject_code', models.CharField(db_index=True, help_text='Subject/course code', max_length=50)),
                ('subject_description', models.CharField(help_text='Full subject description', max_length=255)),
                ('total_academic_units', models.FloatField(help_text='Number of academic units/credits', validators=[core.validators.validate_units])),
                ('final_grade', models.FloatField(help_text='Final grade received (1.0 - 5.0 scale)', validators=[core.validators.validate_grade])),
                ('remarks', models.CharField(blank=True, help_text='Grading remarks (PASSED/FAILED)', max_length=255, null=True)),
                ('summary', models.TextField(blank=True, help_text='Detailed comparison summary', null=True)),
                ('credit_evaluation', models.CharField(choices=[('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Investigate', 'Investigate'), ('Void', 'Void')], db_index=True, default='Void', help_text='Final credit evaluation decision', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from evaluator', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TOR Comparison Result',
                'verbose_name_plural': 'TOR Comparison Results',
                'db_table': 'compare_result_tor',
                'ordering': ['account_id', 'subject_code'],
                'indexes': [models.Index(fields=['account_id', 'subject_code'], name='compare_res_account_634e10_idx'), models.Index(fields=['credit_evaluation'], name='compare_res_credit__1fb18a_idx'), models.Index(fields=['created_at'], name='compare_res_created_c1dbb3_idx')],
                'unique_together': {('account_id', 'subject_code')},
            },
        ),
    ]
