# Generated by Django 5.2 on 2025-12-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareresulttor',
            name='remarks',
            field=models.CharField(blank=True, help_text='Grading remarks (PASSED/FAILED)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='compareresulttor',
            name='subject_description',
            field=models.CharField(help_text='Full subject description', max_length=500),
        ),
    ]
