# Generated by Django 5.2 on 2025-12-08 11:55

import core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(db_index=True, max_length=50, validators=[core.validators.validate_account_id])),
                ('applicant_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], db_index=True, default='Pending', max_length=50)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pending Request',
                'verbose_name_plural': 'Pending Requests',
                'db_table': 'pending_request',
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['applicant_id'], name='pending_req_applica_748c0c_idx'), models.Index(fields=['status'], name='pending_req_status_090033_idx')],
            },
        ),
    ]
